name: NuGet

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: "Github token passed from the caller workflow"
        required: true

jobs:
  test:
    uses: ./.github/workflows/workflow_test.yml

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./csharp

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0 # Don't use @master unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          WITH_V: true

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: .NET Pack
        run: dotnet pack --configuration Release

      - name: .NET NuGet push
        run: dotnet nuget push "src/LookMumNoHandlebars.CallMeOptionally/bin/Release/LookMumNoHandlebars.CallMeOptionally.*.nupkg" --source "github" --api-key {{ }}
